name: RPM

permissions:
  contents: read

on:
  pull_request:
    branches:
      - main
      - v*
  push:
    branches:
      - main
      - v*
    paths-ignore:
      - .gitignore
      - '**.md'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  alma9:
    name: Alma Linux 9
    runs-on: ubuntu-latest
    container: almalinux:9

    steps:
    - name: Install git
      run: yum install -y git

    - name: Clone repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install RPM development tools
      run: |
        dnf install -y epel-release rpmdevtools dnf-plugins-core
        dnf config-manager --set-enabled crb

    - name: Install XRootD build dependencies
      run: dnf builddep -y rpm/xrdcl-pelican.spec

    - name: Build RPMs
      shell: bash
      run: |
        rpmdev-setuptree
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
        export XRDCL_VERSION=$(grep Version rpm/xrdcl-pelican.spec | cut -f 2 -d ' ')
        git archive --prefix xrdcl-pelican-$XRDCL_VERSION/ -o $(rpm -E '%{_sourcedir}')/xrdcl-pelican-$XRDCL_VERSION.tar.gz HEAD
        rpmbuild -bb --with git rpm/xrdcl-pelican.spec

    - name: Install RPMs
      run: dnf install -y $(rpm -E '%{_rpmdir}')/*/*.rpm

    - name: Move RPMs to Artifact Directory
      run: mkdir RPMS && mv $(rpm -E '%{_rpmdir}')/ RPMS$(rpm -E '%{dist}' | tr . /)

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: alma9
        path: RPMS
        retention-days: 14

  alma10beta:
    name: Alma Linux 10
    runs-on: ubuntu-latest
    container: almalinux:10

    steps:
    - name: Install git
      run: yum install -y git

    - name: Clone repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install RPM development tools
      run: |
        dnf install -y epel-release rpmdevtools dnf-plugins-core
        dnf config-manager --set-enabled crb

    - name: Install XRootD build dependencies
      run: dnf builddep -y rpm/xrdcl-pelican.spec

    - name: Build RPMs
      shell: bash
      run: |
        rpmdev-setuptree
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
        export XRDCL_VERSION=$(grep Version rpm/xrdcl-pelican.spec | cut -f 2 -d ' ')
        git archive --prefix xrdcl-pelican-$XRDCL_VERSION/ -o $(rpm -E '%{_sourcedir}')/xrdcl-pelican-$XRDCL_VERSION.tar.gz HEAD
        rpmbuild -bb --with git rpm/xrdcl-pelican.spec

    - name: Install RPMs
      run: dnf install -y $(rpm -E '%{_rpmdir}')/*/*.rpm

    - name: Move RPMs to Artifact Directory
      run: mkdir RPMS && mv $(rpm -E '%{_rpmdir}')/ RPMS$(rpm -E '%{dist}' | tr . /)

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: alma10
        path: RPMS
        retention-days: 14
