name: Test

on:
  workflow_dispatch:
    branches:
      - main
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  BUILD_TYPE: Debug

jobs:
  build:
    strategy:
      matrix:
        external-gtest: [ YES ]
        os: [ ubuntu-24.04 ]

    runs-on: ${{ matrix.os }}
    name: Build with external_gtest=${{ matrix.external-gtest }} on ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: actions/setup-go@v5
    - name: install deps
      working-directory: ${{runner.workspace}}
      run: |
        # Build deps
        sudo apt update && sudo apt-get install -y cmake libz-dev uuid-dev libcurl4-openssl-dev libcurl4 pkg-config libssl-dev g++ libscitokens-dev libgtest-dev

        # Build our preferred set of patches on xrootd
        git clone https://github.com/xrootd/xrootd.git
        cd xrootd
        git remote add github_pelican https://github.com/PelicanPlatform/xrootd.git
        git fetch github_pelican
        git checkout -b v5.8.4-pelican -t github_pelican/v5.8.4-pelican
        mkdir -p build/release_dir
        cd build
        cmake .. -DCMAKE_INSTALL_PREFIX=$PWD/release_dir -DENABLE_ASAN=TRUE
        make -j $(($(nproc) + 2)) install

        # Install the load tester
        go install github.com/bbockelm/go-wrk@92dbe19

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: CMAKE_PREFIX_PATH=$PWD/../xrootd/build/release_dir/lib/cmake/XRootD cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DENABLE_ASAN=true -DENABLE_TESTS=true

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: cmake --build . --config $BUILD_TYPE --parallel $(($(nproc) + 2))

    - name: Unit Tests
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: |
        (XRD_LOGLEVEL=Debug ctest -C $BUILD_TYPE --timeout 60 --verbose -R basic::test || ( cat tests/basic/pelican.log && exit 1 ) ) &&
        XRD_LOGLEVEL=Debug ctest -C $BUILD_TYPE -V -R CurlCalloutFixture.Test
        ctest -C $BUILD_TYPE --timeout 60 --verbose -E CurlCalloutFixture.Test
